name: pullrequest

on:
  pull_request:
    branches:
      - master

jobs:
  pullrequest:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh/
          echo -e 'Host *\n\tStrictHostKeyChecking no\n\n' > ~/.ssh/config
          echo "${{ secrets.SSH_KEY_KSF }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

      - name: Deploy 🚀
        run: docker-compose up -d --build
        env:
          DOCKER_HOST: ssh://${{ secrets.SSH_USER_KSF }}@${{ secrets.SSH_HOST_KSF }}
